### ISSUE TITLE
Section Addressed Challenges

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#34]
Inside the contribution section  some structural stuff needs to be done. We can try to discuss upcoming questions that are relevant for all, here as well.

- If there is more to come (what I think it will) we might want to present an on section
- Check with #32 , for the table of challenges (coherence) 
- come up with a good structure 
- think about missing or under represented points  
- Is this already the discussion ? Or what do we discussion in the 'discussion' section'. This needs to be considered as well

**Comment by simnh** [comment]
If we make a own section for 'contribution', we could have a subsection discussion there as well which might resolve problems.

**Comment by simnh** [comment]
Some ideas / hints from the comments for structure: "Open", "Collaborative", 'Structural' and "overview" 

- general points of what contributes to what that is written at
the beginning of the chapter at the moment to the "overview" subsection
- Underpin contribution with figure 
- Move table to discussion 
- Refer more on that section uncertainty inside contribution.

}

**Comment by ckaldemeyer** [comment]
> If we make a own section for 'contribution', we could have a subsection discussion there as well which might resolve problems.

I think if we have an own section (wouldn't it be a chapter?) for the contribution it emphasizes the message of the paper.

> Move table to discussion

Either to the discussion or even to the conclusion.

**Comment by simnh** [comment]
> Either to the discussion or even to the conclusion.

Yeah, this was meant by it (because right now its the same section/chapter)

**Comment by cswh** [comment]
I think:
* What now is "Contribution" should be a chapter/section on its own.
* Section "The Framework" should be renamed into "The Framework Concept and Applications".
* Section "Contribution" should be renamed into "oemof's Contributions" or "Challenges addressed" or something similar, because just "contribution" could be understood as well who contributed to the framework etc.
* That section should focus solely on what challenges are adressed directly by oemof (and perhaps low hanging indirect fruits).
* Future possibiliities on how it can address more should be in the "Discussion and Conclusion" sector. Saying as well that the general oemof approach ("the addressed challenges described in contribution) lay the foundation for some of the other challenges.

**Comment by ckaldemeyer** [comment]
> Section "The Framework" should be renamed into "The Framework Concept and Applications".

Would it even make sense to divide it in two sections ("The Framework and its concept" and "Possible Applications"?

I am not quite sure myself but it might emphasize the idea of versatility and flexibility behind it..

> Future possibiliities on how it can address more should be in the "Discussion and Conclusion" sector. Saying as well that the general oemof approach ("the addressed challenges described in contribution) lay the foundation for some of the other challenges.

I like the idea to have an outlook of what it could become!

**Comment by simnh** [comment]
Ok we will have a extra contribution, disscussion and conclusion section each...

**Comment by ckaldemeyer** [comment]
> Is this already the discussion ? Or what do we discussion in the 'discussion' section'. This needs to be considered as well

I now see what you mean. The section "Addressed challenges" already contains a lot of discussion and thus the section "Discussion" is hard to fill up. It seems a bit redundant to me and it might be an idea to combine both sections.

**Comment by ckaldemeyer** [comment]
So we could just drop the "Discussion" and find a nice internal structure for "Addressed challenges" or "Challenges tackled by oemof" or something similar..

**Comment by ckaldemeyer** [comment]
I am working on this now..

**Comment by ckaldemeyer** [comment]
Here's my proposed structure:

* Section "Addressed challenges"
  * Introduction
  * Methodology (contributions based on 3 characteristics (open source, collaborative, structural properties) that can be assigned to each challenge)
  * Contribution (one paragraph per challenge)
    * By which characteristics is the challenge tackled?
    * To what extend right now?
    * Provide exampes and be illustrative
  * Bridge passage to discussion

* Section "Discussion" 
  * Why can certain challenges not be tackled?
  * What are the difficulties in addressing this challenge?
  * Are the difficulties problem-specific or could they be addressed by potential future developments within oemof?

**Comment by fraukewiese** [comment]
I think it is good that it is called addressed challenges now and separated from the discussion. I would recommend to stick for the structure to what is there now, but to separate, as you propose the three characteristics and what they contribute. You can clearly build on what is there, just order it. Otherwise it is too much new work. And I would recommend to already refer to oemof in there and not, first 3 times contribution of charactersitic and then 3 times contribution of characteristic of oemof, that makes too much repeating.
I would really recommend a figure for that, just a very rough illustration of what I mean: https://github.com/simnh/addressing_challenges_oemof/blob/master/figures/suggested_figure_for_contributions.png
What do you think?

**Comment by ckaldemeyer** [comment]
> I think it is good that it is called addressed challenges now and separated from the discussion. I would recommend to stick for the structure to what is there now, but to separate, as you propose the three characteristics and what they contribute. You can clearly build on what is there, just order it. Otherwise it is too much new work.

I know that this is new work but I think it's much easier to understand from an "unware-reader-perspective" to go from challenge to challenge. We have two tables with challenges (in the beginning and in the end) and I sometimes myself have to lookup "What was this challenge, again?". If we now introduce the three properties and go property by property it kind of changes the perspective (from my point of view) which might be confusing.

> And I would recommend to already refer to oemof in there and not, first 3 times contribution of charactersitic and then 3 times contribution of characteristic of oemof, that makes too much repeating.

I agree to that. Only oemof-specific..

> I would really recommend a figure for that, just a very rough illustration of what I mean: https://github.com/simnh/addressing_challenges_oemof/blob/master/figures/suggested_figure_for_contributions.png

See above.

**Comment by simnh** [comment]
@ckaldemeyer  will you be able to present the new contribution with the figure, we can extend afterwards

**Comment by fraukewiese** [comment]
@ckaldemeyer : I will be happy with the structure you propose. I there is something tomorrow (Friday 23rd December) morning, I can build on that for the discussion. So feel free to also push intermediate steps / just let me know the structure

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer will you be able to present the new contribution with the figure, we can extend afterwards

So I should create a figure to discuss it before writing? Yes, I can do that!

> @ckaldemeyer : I will be happy with the structure you propose. I there is something tomorrow (Friday 23rd December) morning, I can build on that for the discussion. So feel free to also push intermediate steps / just let me know the structure

I'll push in small steps!

**Comment by fraukewiese** [comment]
cool!
Verortung in papern zur Reproduzierbarkeit / Transparency Checklists is as a \todo in Discussion #50 now. As it is directly about what oemof contributes, shouldn't it be in the addressed challenges section? @ckaldemeyer

**Comment by simnh** [comment]
yes we should do that I think (if we comply, if not, it would go to discussion). Addtionally, this should then (if not inside discussion, but maybe even then) added to the scientific standards section. but very briefly as this section is already quite long

**Comment by ckaldemeyer** [comment]
> Verortung in papern zur Reproduzierbarkeit / Transparency Checklists is as a \todo in Discussion #50 now. As it is directly about what oemof contributes, shouldn't it be in the addressed challenges section? @ckaldemeyer

:+1:

**Comment by ckaldemeyer** [comment]
I think @fraukewiese 's figure doesn't have to be changed because it could be the foundation for both, the characteristic-wise and challenge-wise structure of the section.

My suggested structure can be found in the list above but I just had the idea to amend something!

What about an amended table 2 that provides a combination of the challenges, the addressment by oemof's characteristics and the arguments for it similar to @fraukewiese 's figure. This would be concrete and quite self-explaining.

Here's a proposal for the Table2:

| Challenge            | Degree of addressment | Addressed through oemof's characteristics        | Arguments                                                                              |
|----------------------|-----------------------|--------------------------------------------------|----------------------------------------------------------------------------------------|
| Complexity           | +                     | collaborative development, structural properties |                                                                                        |
| Uncertainty          | -                     | collaborative development                        | no stochastic approaches                                                               |
| Interdisciplinarity  | o                     | collaborative development, structural properties |                                                                                        |
| Scientific standards | +                     | open source, collaborative development           | open source and open data, extensive documentation                                     |
| Model utilisation    | o                     | collaborative development, structural properties | documentation, collaborative development, con:developer/user- decision maker interface | 

It could be placed in the section "Addressed challenges" right before the "arguments" for each challenge are explained in single paragraphs and visualle make the link between characteristics and challenges. Or we just leave it in the section "Conclusion" as it is now..

So the full amended suggested structure for the section would look like this:

  *  Introduction
     * Contributions based on 3 characteristics
     * Mentioning or listing of 5 challenges as proposed by @gplssm in a comment
  * Table2 (see above)
  * oemof's addressment (one longer paragraph per challenge)
    * By which characteristics is the challenge tackled?
    * To what extend right now?
    * Provide exampes and be illustrative
  * Bridge passage to discussion

What do you think? @simnh @fraukewiese @gplssm @cswh @uvchik @gnn  

If you agree I will start writing..

**Comment by simnh** [comment]
I really like the table, but I am not sure which place is best and if it fully replaces the figure (which I like as well). But I think just start and do the addressed section as you proposed. There are many good ways and yours is certainly on of them!  

I generally think if the table goes to conclusion or addressed challenges depend on what goes to the discussion (only discussion of general problems and the methodologyor of the challenges) 

Maybe this can be an approach: 

- Addressed challenges will get the first part of the discussion with redard to 'partliy' and 'not addressed' (maybe even with an own section 
- Discussion gets only discussion of general problems and our methodology etc. 

Either way, your structure for the addressed challenges should  do it anyway!

**Comment by ckaldemeyer** [comment]
> I generally think if the table goes to conclusion or addressed challenges depend on what goes to the discussion (only discussion of general problems and the methodologyor of the challenges)

For me the section "Conclusion" puts the section "Addressed Challenges" and "Discussion" in a nutshell without adding anything new. It could contain the table but doesn't have to. I would tend to put it in the contribution and have the conclusion really short..

> Maybe this can be an approach:
> Addressed challenges will get the first part of the discussion with redard to 'partliy' and 'not addressed' (maybe even with an own section
> Discussion gets only discussion of general problems and our methodology etc.

Sounds good. I will start now.

**Comment by ckaldemeyer** [comment]
> I really like the table, but I am not sure which place is best and if it fully replaces the figure (which I like as well). 

I would tend to use either a table or a figure and to somehow add the information of each other and make it complete.

**Comment by simnh** [comment]
table

**Comment by fraukewiese** [comment]
sounds good to me, I have pushed some changes for discussion, see #50 . In there are some paragraphs that would rather fit into addressed challenges, so you might have a look at these @ckaldemeyer and take them. I have started the discussion with one paragraph summarizing and referring to the table you mentioned. The extension also fits well. I can fit in addressed challenges or beginning of discussion, you will figure out what is better :)

**Comment by ckaldemeyer** [comment]
> sounds good to me, I have pushed some changes for discussion, see #50 . In there are some paragraphs that would rather fit into addressed challenges, so you might have a look at these @ckaldemeyer and take them.

Thanks, I'll have a look!

For your information: I'll just start now for 30 minutes and then I'll be away for christmas and holiday until January 2nd. Just haning arround, beeing outside and not in front of a computer that much... ;-)

Merry christmas and a happy new year to all of you!

**Comment by ckaldemeyer** [comment]
Finito. See you!

**Comment by ckaldemeyer** [comment]
Memo: We comply with the science code manifesto (http://sciencecodemanifesto.org/)

**Comment by ckaldemeyer** [comment]
Sprechen wir eigentlich von "characteristics" oder von "properties"? 

Habe jetzt erstmal alles auf "characteristics" geändert aber bin mir nicht sicher, ob der Begriff wirklich besser ist..

**Comment by ckaldemeyer** [comment]
Also "oemof's characteristics" = collaborative development, structural properties, ...

**Comment by simnh** [comment]
Denke das characteristics besser ist, dann bleibt properties für structural properties ....und collaborative development ist ja auch nicht wirklich eine Eigenschaft sonder eher eine charateristik .-/ ? ...Ne, mal im Erstn, ich glaub das passt erstmal so

**Comment by ckaldemeyer** [comment]
> collaborative development ist ja auch nicht wirklich eine Eigenschaft sonder eher eine charateristik :-/ ? 

Ich würde das jetzt nicht nachschlagen wollen.. Aber für mich passt es sonst auch erstmal so. Eigentlich isses auch wumpe, solange man die Begriffe selbst besetzt und stringent verwendet.

**Comment by uvchik** [comment]
Properties im Sinne von Merkmal geht auch, aber ich denke auch das in dem Zusammenhang characteristic häufiger benutzt wird.
