### ISSUE TITLE
Check table in Addressed Challenges

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#69]
Can you revise this one an add missing information or correct minor errors etc.? 

https://github.com/simnh/addressing_challenges_oemof/blob/master/addressing_energy_system_modelling_challenges.tex#L1457-L1488

**Comment by fraukewiese** [comment]
revised, pushed.
Just minor formal stuff and I added reproducibility as an argument to scientific standards.
I think Characteristic (1) free & open philosophy could also be put to complexity, interdisciplinarity, model utilisation, because it lays the foundation /enables to tackle these challenges. But I did not write it yet, as it could be a matter of taste and leave it to you whether you think so too

**Comment by simnh** [comment]
thanks, I agree, but as they are rather the foundation, I like to keep it distinct. This makes being precise a lot easier inside the text...
BTW: up to now collabrative development is not even mentioned in the complexity section. I think it ok to focus on the major aspects here...

**Comment by simnh** [comment]
but in model utilisation it should definitely pop up
