### ISSUE TITLE
Last proofreading

### ISSUE THREAD

**Issue by fraukewiese** [simnh/addressing_challenges_oemof#76]
Habe jetzt alles gelesen und Rechtschreibfehler, Kommas, Tabellenverweis, Referenznenneung-Einheitlichkeit und etwas Sprache korrigiert. Da war doch noch so einiges. 

Folgendes habe ich noch nicht geändert, muss aber noch:
- Simon bei der Autorennennung herausheben als mehr beigetragen, nicht equally zu uns anderen, das fänd ich sonst unfair für Simon.
- Günnis Kommentar auf Seite 12 weg
- Kommentar auf Seite 18 weg
- Cords Kommentar auf Seite 20 weg. Meine inhaltliche Antwort darauf: Ist ja ne Art Discussion in der das steht. Da darf man auch mal so ne Aussage raushauen, sonst ist das doch alles zu langweilig. Bin aber nicht traurig wenn ihr den Satz rausnehmt wenn ihr das da nicht drin haben wollt
- Seite 22 ToDos raus

Vorschlag: Dienstag 14.Februar einreichen

Danke @simnh @ckaldemeyer !

**Comment by gplssm** [comment]
Danke für die ganze Vorarbeit, Frauke! Ich hatte an Rechtschreibfehlern nicht mehr soviel zu verbessern.

Meine übergreifende Beurteilung: das Paper kann so eingereicht werden.
Sicherlich gibt es überall noch Detailverbesserungspotenzial, aber so wie es aussieht, hat auch gerade niemand direkt Zeit dafür. Deshalb: einreichen und Feedback abwarten. Die werden uns nicht den Kopf abreißen.
Wenn jemand von euch wirklich noch Muße hat, kann ich empfehlen das "Addressed challenges" Kapitel nochmal mit dem Challenges-Kapitel abzugleichen. Idealerweise sollten alle Aspekte die dort thematisiert wurden am Ende auch wieder aufgegriffen werden.

Neben kleinen Änderungen, die ich ohne Rücksprache in den Master-Branch committed habe, gibt es noch ein paar Änderungsvorschläge die abgesegnet werden sollten: #78

Ich habe noch eine Liste an Änderungswünschen für die ich keinen guten Vorschlag machen konnte/ die ich anderen zuordne

- [ ] Mir wird [hier](https://github.com/simnh/addressing_challenges_oemof/blob/94dc775bd41e243cb468a8c5080c9d08b9774781/addressing_energy_system_modelling_challenges.tex#L408-#L410) nicht genau klar was gemeint ist. Was bedeutet z.B. "opaque" in diesem Kontext?
- [ ] "sophisticated" ist [hier](https://github.com/simnh/addressing_challenges_oemof/blob/94dc775bd41e243cb468a8c5080c9d08b9774781/addressing_energy_system_modelling_challenges.tex#L535) glaub ich das falsche Wort. Ich konnte es nicht ändern, weil mir die beabsichtigte Aussage nicht klar ist.
- [ ] Mir wird die Aussage [des Satzes](https://github.com/simnh/addressing_challenges_oemof/blob/94dc775bd41e243cb468a8c5080c9d08b9774781/addressing_energy_system_modelling_challenges.tex#L1465-#L1467) nicht klar.
- [ ] Für mich ist [Punkt (1)](https://github.com/simnh/addressing_challenges_oemof/blob/94dc775bd41e243cb468a8c5080c9d08b9774781/addressing_energy_system_modelling_challenges.tex#L1501-#L1503) nicht verständlich
- [ ] [Dieser Absatz](https://github.com/simnh/addressing_challenges_oemof/blob/94dc775bd41e243cb468a8c5080c9d08b9774781/addressing_energy_system_modelling_challenges.tex#L1528-#L1533) könnte noch klarer gemacht werden
- [ ] Welches interface ist [hier](https://github.com/simnh/addressing_challenges_oemof/blob/94dc775bd41e243cb468a8c5080c9d08b9774781/addressing_energy_system_modelling_challenges.tex#L1652) gemeint?
- [ ] ich verstehe dieses Format bei Zitaten nicht: [m]odellers need to engage with
their beneficiaries from the outset so that models are properly scoped and
fit for purpose. warum wird der erste Buchstabe in [] gesetzt? (taucht häufiger auf)
- [ ]  @gnn: kannst du bitte in Fig 3 noch die Assoziation zu Flow Objekten aufnehmen?
- [ ] Gegenwärtig existiert ein mix aus den Schreibweisen oemof-solph und oemof.network. Das sollte enheitlich, oder? Welches ist "die richtige" Schreibweise?
- [ ] Wollen wir bei Referenzierungen Fig, Fig. oder Figure schreiben? Macht PLOS1 Vorgaben?
- [ ] Schreiben wird decision-maker oder decision maker? Gegenwärtig existiert beides.
- [ ] Der begleitende Text zu Fig 5 sollte sich näher an der Grafik orientieren und bspw. die Begriffe ausgreifen.

:+1: für Einreichung am 14.2.! @uvchik @gnn @cswh könnt ihr dafür auch noch grünes Licht geben bzw. ne Ansage machen bis wann ihr noch Zeit braucht um euer Feedback abzugeben?

**Comment by simnh** [comment]
Dank Guido! 
Ich werde ein paar Sachen von dem oben gennanten machen...

> Mir wird hier nicht genau klar was gemeint ist. Was bedeutet z.B. "opaque" in diesem Kontext?
Es meint 'undurchsichtig', wäre obscure besser?

**Comment by simnh** [comment]
> ich verstehe dieses Format bei Zitaten nicht: [m]odellers need to engage with
their beneficiaries from the outset so that models are properly scoped and
fit for purpose. warum wird der erste Buchstabe in [] gesetzt? (taucht häufiger auf)

Da das Zitat eingebettet in den 'normalen' Satz ist, muss ja im Satz kleingeschrieben werden, aber im original text ist es halt ein eigener satz, daher ist wird aus einem satz anfang wie bei: "Modeller..." dann " ..., [m]odeller...". Ich meine es wäre so richtig, korrigiert mich, wenn ich falsch liege?

**Comment by gplssm** [comment]
Danke für die flinke Reaktion in commits und Rückmeldung! :+1: 

> > Mir wird hier nicht genau klar was gemeint ist. Was bedeutet z.B. "opaque" in diesem Kontext?
> 
> Es meint 'undurchsichtig', wäre obscure besser? 

Vielleicht ist die Frage auch eher was der Satz intendiert... ;) Soll ausgesagt werden, dass es für Aussenstehende schwer ist die Energiesystemmodellierungswelt zu überblick und deshalb bspw. Taxonomien eine klasse Sache sind?

Ich habe einige Punkte als erledigt geklickt.

Bei der Diskussion um _Interdisciplinary modelling_ habe ich nochmal Hand angelegt #79. Bin mir aber auch nicht mehr sicher, ob ich wirklich besser finden soll als die vorherige Version... It's up to you @simnh

**Comment by ckaldemeyer** [comment]
Danke @fraukewiese @gplssm und @simnh !

> Cords Kommentar auf Seite 20 weg. Meine inhaltliche Antwort darauf: Ist ja ne Art Discussion in der das steht. Da darf man auch mal so ne Aussage raushauen, sonst ist das doch alles zu langweilig. Bin aber nicht traurig wenn ihr den Satz rausnehmt wenn ihr das da nicht drin haben wollt

Ich finde den Gedanken grundsätzlich interessant und man kann an geeigneter Stelle natürlich auch mal eine Aussagen raushauen. Hier würde ich allerdings wenigstens irgendein Beispiel anführen weil ich mich tatsächlich Frage an welcher Stelle bzw. wo diese "Diskriminierung" auftritt. Oder halt umformulieren und ein wenig entschärfen. In nem Essay oder Position Paper kann man das schon so machen, in nem Journal m. E.  eher nicht.

@gplssm s Todos sehe ich wie @simnh und finde die Punkte durchweg angebracht.

Auf jeden Fall finde ich es krass wieviel man immer noch findet, obwohl man schon 2x über das Paper gegangen ist ;)

**Comment by ckaldemeyer** [comment]
Habe mir gerade nochmal das Abstract angeschaut und finde, dass man daran nochmal pfeilen kann.

Der Anfagssatz

`The process of modelling energy systems is accompanied by challenges inherently
connected with mathematical modelling.`

ist m. E. schon recht spezifisch und ich würde eher generell mit Komplexität, Interdisziplinarität, etc. anfangen.

**Comment by ckaldemeyer** [comment]
Vielleicht können @cswh @gnn oder @uvchik ja noch einmal draufschauen

**Comment by ckaldemeyer** [comment]
> Simon bei der Autorennennung herausheben als mehr beigetragen, nicht equally zu uns anderen, das fänd ich sonst unfair für Simon.

Ich fände es auch in Ordnung Simon mehr herauszuheben wobei der corresponding author und der Name an erster Stelle den höheren Anteil meiner Meinung nach schon ausdrückt.

Die einzelnen Paperanteile kann man auch hier -zumindest quantitativ- nochmal gut grob nachverfolgen: https://github.com/simnh/addressing_challenges_oemof/graphs/contributors

Abzüglich der Zeilen für Abbildungen, etc.. ;)

**Comment by ckaldemeyer** [comment]
Könnte man ja auch nochmal in den Acknowledgements aufnehmen...haha

**Comment by cswh** [comment]
> Vielleicht können @cswh @gnn oder @uvchik ja noch einmal draufschauen

Ich hatte es Simon auch angeboten nochmal drüberzuschauen, er meinte es wäre nicht notwendig. Ich würde es eher sehr zeitnah einreichen und auf die comments der reviewer warten. Dann ist bestimmt auch nochmal was zu tun. Außer @simnh meint ich soll nochmal drauf schauen.

**Comment by ckaldemeyer** [comment]
> Ich hatte es Simon auch angeboten nochmal drüberzuschauen, er meinte es wäre nicht notwendig. Ich würde es eher sehr zeitnah einreichen und auf die comments der reviewer warten. Dann ist bestimmt auch nochmal was zu tun. Außer @simnh meint ich soll nochmal drauf schauen.

Er soll das entscheiden. Wobei ich dem Abstract wie gesagt nochmal ne halbe Stunde gönnen würde. Egal, ich sag jetzt nichts mehr und bin bis nach dem Reviewprozess raus ;)

**Comment by uvchik** [comment]
Ich würde es morgen (Dienstag) Vormittag nochmal lesen, wenn das noch gewünscht ist. 

Würde klitze kleine Änderungen direkt ändern (PR) und mir sonst nur eigene Notizen für den Review-Prozess machen. Glaube aber nicht, dass noch was sein wird, wenn so viele schon drüber gelesen haben.

**Comment by simnh** [comment]
Ja gerne, Uwe! Aber lieber nur Rechtschreibung und offensichtliche Schnitzer...Wir sind inzwischen an einem Punkt wo wir viel über 'gemschack' von nicht native speaker sprechen haben ich das Gefühl. 

Und natürlich Was hilf Sachen zu präzisieren und ergänzen, wenn wichtiges fehlt. 

Ich lese morgen früh vor 10:00 auch noch mal den Rest. Dann ist es für mich erstmal durch, bin irgendwie gar nicht mehr zufrieden, aber soll jetzt ja einfach mal raus...

**Comment by gplssm** [comment]
Kopf hoch, Simon! Du wirst das Paper auch wieder mögen :)

**Comment by gplssm** [comment]
@simnh kannst du bei der Sumbission den Preprint auch direkt bei arxiv.org hochladen und den Link posten? Dann könnte ich das an Hans-Kristjan weitergeben, der das Paper zitieren wollte.

Wenn du nur noch submitten und dann erst mal Ruhe haben willst, kann ich das übernehmen.

**Comment by simnh** [comment]
@uvchik : du bist nun der letzte leser...

@gplssm 
Aber dann müssen wir das in ein anderes latex format bringen oder? Mal sehen, ich werde es morgen erstmal einreichen....

**Comment by gplssm** [comment]
Hmm. Ehrlich gesagt, habe ich arxiv.org noch nie benutzt und dachte man lädt das da einfach so hoch... Müsste ich mir auch anschauen. Gib einfach Bescheid falls du es gemacht hast oder du es nicht machen magst. Dann würde ich es mir anschauen.

**Comment by simnh** [comment]
Ne so wie ich dass weiß muss man halt ein einfachs latex template nehmen ohne journal zeugs...zumindest bei den preprints die ich mir angeguct habe

**Comment by ckaldemeyer** [comment]
> Kopf hoch, Simon! Du wirst das Paper auch wieder mögen :)

Ich glaube das ist der normale Prozess und ich finde wir können Stolz auf uns bzw. dich Simon sein, dass wir das Paper -wenn auch in der ersten Version, ohne Review- endlich fertig haben.

Das Paper füllt m. E. ein Vakuum, dass schon lange besteht!

**Comment by simnh** [comment]
@uvchik @gplssm  : Habt ihr ein 'Department' das sollte dann noch bei euch auftauchen. Außerdem den Namen von RLI in englisch

**Comment by ckaldemeyer** [comment]
Und es wird nach dem Review ohnehin nochmal verbessert..

**Comment by cswh** [comment]
wegen preprint:

> We ask that you include the DOI of your preprint, if available, with your PLOS submission to facilitate linking between the preprint and the accepted peer-reviewed article upon publication.

from http://journals.plos.org/plosone/s/ethical-publishing-practice#loc-preprint-servers

**Comment by uvchik** [comment]
Das RLI hat keinen englischen Namen und daher würde ich den auch so beibehalten. Habe noch das kleine 'g' ergänzt, denn wir sind eine gemeinnützige Gesellschaft. Offizielle Abteilungen haben wir nicht.

Ansonsten habe ich nichts gefunden, was ich zum jetzigen Zeitpunkt noch anmerken würde.

Die Fig.  2 ist falsch, aber da sie sowieso der zeitlichen Veränderung unterworfen ist, würde ich sie erst nach dem Review anpassen. Wer weiß was sich bis dahin wieder ändert :smirk: 

Vielen Dank an @simnh und alle anderen Beitragenden. Jetzt ist wohl Schulterklopfen angesagt :tada:

**Comment by gplssm** [comment]
> wegen preprint:
> 
> > We ask that you include the DOI of your preprint, if available, with your PLOS submission to facilitate linking between the preprint and the accepted peer-reviewed article upon publication.
> 
> from http://journals.plos.org/plosone/s/ethical-publishing-practice#loc-preprint-servers

[arxiv.org does not provide DOIs](https://academia.stackexchange.com/questions/62480/why-does-arxiv-org-not-assign-dois), but we could provide the arxiv reference if the can work with.

**Comment by uvchik** [comment]
Shall we announce the preprint on our [website](https://oemof.org/news/)?

**Comment by simnh** [comment]
good idea...where it makes sense
when you announce it, also state that  feedback is welcome on preprints.org.

**Comment by ckaldemeyer** [comment]
> good idea...where it makes sense
> when you announce it, also state that feedback is welcome on preprints.org.

:+1:

**Comment by uvchik** [comment]
Like this? https://oemof.wordpress.com/wp-admin/post.php?post=488&action=edit

**Comment by ckaldemeyer** [comment]
I would name the title "Preprint of oemof research paper published" and then start with

"A research paper that analyses how oemof addresses actual and future challenges in energy system modelling has been published by Simon Hilpert and co-authors in a preprint version. Feedback is highly appreciated!"

TEXT

If you want to cite the paper you can use the following format:

Hilpert, S.; Günther, S.; Kaldemeyer, C.; Krien, U.; Plessmann, G.; Wiese, F.; Wingenbach, C. Addressing Energy System Modelling Challenges: The Contribution of the Open Energy Modelling Framework (oemof). Preprints 2017, 2017020055 (doi: 10.20944/preprints201702.0055.v1).

**Comment by simnh** [comment]
I would add the link for preprints, where comments etc. should be made...that should be the most transparent way in terms of feedback:

http://www.preprints.org/manuscript/201702.0055/v1

**Comment by uvchik** [comment]
Thank you for the feedback.
